name: Publish package to PyPI

on:
  release:
    types: [published]   # it start when i publish a release on GitHub

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clone repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2️⃣ Set Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Install needed tools
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # 4️⃣ Compile package (sdist + wheel)
      - name: Build package
        run: python -m build

      # 5️⃣ Pubblish on PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
